#!/bin/bash

read -p "number" a

if (($a % 3 == 0)) || (($a % 5 == 0)) || (($a % 7 == 0))
    then 
	echo "Number is divisible by 3 or 5 or 7"
    else
	echo "Number is not divisible by 3 or 5 or 7"
fi	

